export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';
export const FETCH_TRACKS_FAIL = 'FETCH_TRACKS_FAIL';
export const TRACK_HAS_BEEN_LISTENED = 'TRACK_HAS_BEEN_LISTENED';
export const REFRESH_LISTENED_TRACKS = 'REFRESH_LISTENED_TRACKS';

export const FETCH_PLAYLISTS_SUCCESS = 'FETCH_PLAYLISTS_SUCCESS';
export const FETCH_PLAYLISTS_FAIL = 'FETCH_PLAYLISTS_FAIL';
export const DELETE_PLAYLISTS_SUCCESS = 'DELETE_PLAYLISTS_SUCCESS';
export const DELETE_PLAYLISTS_FAIL = 'DELETE_PLAYLISTS_FAIL';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAIL = 'CREATE_PLAYLIST_FAIL';
export const ADD_TRACK_TO_PLAYLIST_SUCCESS = 'ADD_TRACK_TO_PLAYLIST_SUCCESS';
export const ADD_TRACK_TO_PLAYLIST_FAIL = 'ADD_TRACK_TO_PLAYLIST_FAIL';
export const REMOVE_TRACK_FROM_PLAYLIST_SUCCESS = 'REMOVE_TRACK_FROM_PLAYLIST_SUCCESS';
export const REMOVE_TRACK_FROM_PLAYLIST_FAIL = 'REMOVE_TRACK_FROM_PLAYLIST_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_TOKENS = 'REFRESH_TOKENS';

export const REGISTER_START =  'REGISTER_START';
export const REGISTER_SUCCESS =  'REGISTER_SUCCESS';
export const REGISTER_FAIL =  'REGISTER_FAIL';

export const REFRESH_QUEUE = 'REFRESH_QUEUE';
export const TRACK_ADDED_TO_QUEUE = 'TRACK_ADDED_TO_QUEUE';
export const TRACK_REMOVED_FROM_QUEUE = 'TRACK_REMOVED_FROM_QUEUE';
export const PLAYLIST_ADDED_TO_QUEUE = 'PLAYLIST_ADDED_TO_QUEUE';